### ISSUE TITLE
Form is sent even if you have not solved the captcha

### ISSUE THREAD

**Issue by Jalkhov** [KnugiHK/flask-hcaptcha#3]
I have followed the steps to the letter and the captcha is displayed correctly, but when I fill in all the fields of the form and press submit the data is sent even if I have not validated the captcha, why is this? I leave the code of my form.

```
<form id="regform" action="{{ url_for('doreg') }}" method="post">
    <label for="r.user"><b>Username</b></label>
    <input type="text" name="r.user" class="smooth" autocomplete="off" maxlength="15" required onkeyup="this.value = this.value.toLowerCase();">
    <label for="r.email"><b>Email</b></label>
    <input type="email" name="r.email" class="smooth" autocomplete="off" maxlength="60" required>

    {{ hcaptcha }}
    <button type="submit" class="btn btn-b btn-sm smooth">Register</button>
</form>
```

**Comment by KnugiHK** [comment]
Sorry for the late reply. It is probably because hCaptcha will not check if the captcha is being done or not in the front-end. If you want to check it in your front-end, you can check if the attribute "data-hcaptcha-response" in the hCaptcha iframe is empty or not.
